### ISSUE TITLE
Rider 2023.2 background colors broken

### ISSUE THREAD

**Issue by DanMcLaughlin** [Hiberbee/code-highlight-themes#101]
**Describe the bug**
Updating to July 31, 2023 update the editor background colors appear to be broken

![image](https://github.com/hiberbee/themes/assets/4943582/e2f350d6-659a-41e1-bd88-c5707f692534)

With this one they've introduced the 'Modern UI', I tried it (I think it looks terrible and went back), but the background colors appear to be the low contrast washed out defaults. To make sure I fully reinstalled the plugin but it persists. 

**To Reproduce**
Upgrade to latest version. Appearance set to Hiberbee Dark as is Editor Color scheme

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Window 11, latest

**Comment by vladyslavvolkov** [comment]
@DanMcLaughlin please, check on latest update, that should be fixed.

**Comment by vladyslavvolkov** [comment]
Frankly, just realized, taking background color sample from your screenshot, that most likely you navigating to read-only file (e.g. third-party source library). I've set different background colors intentionally - for read-only and editable files as of #272625 and #171615 respectively. That will help quickly recover where you are at current navigation and view. 

Check my assumption, maybe that's it. If not, feel free to reopen this issue and add more context so I can assist. Checked 2023.2 Rider, it is aligned with IDEA platform as much as possible
