### ISSUE TITLE
Selected area color bug

### ISSUE THREAD

**Issue by EVA09** [Hiberbee/code-highlight-themes#104]
**Describe the bug**
Selected area color bug,It is not possible to distinguish between the selected areas

**Screenshots**
![image](https://github.com/hiberbee/themes/assets/17931839/9194758e-cf4e-4e6b-b7ce-d3e346232ef3)

**Desktop (please complete the following information):**
 - OS:  Windows
 - Version: Windows11 22H2   phpstorm #PS-232.9921.55   bee ver.2023.9.18.1533

**Comment by jancoufal** [comment]
On my setup it is completely invisible.
* OS: MacOS
* IDEA 2023.2.2 (Ultimate Edition), Build #IU-232.9921.47, built on September 12, 2023
* Hiberbee Theme 2023.9.18.1533
Edit: I've overridden value in my configuration - so selection is visible same as @EVA09's.

**Comment by lev-slinsen** [comment]
Can confirm, windows 10 here, PyCharm build #PC-232.9559.58, plugin version 2023.9.18.1533. Until I updated this morning, everything was looking fine.

**Comment by huzvanec** [comment]
Can confirm - Debian 12, IntelliJ IDEA #IU-232.9921.47, plugin version 2023.9.18.1533

For those who are looking for a quick manual fix, you can edit the background selection color in
Settings -> Editor -> Color Scheme (expand tree ⌄) -> General -> Editor -> Selection Background -> Background (color selection in the right panel)

**Comment by EVA09** [comment]
@Mandlemankiller  I'll tell a joke, my fix is to use the Dracula theme，the work is good
![image](https://github.com/hiberbee/themes/assets/17931839/d55abad5-9773-4949-a891-b2f3a2a0c212)

### **This may be an act of betrayal, but it's okay. I'll be back.**

**Comment by vladyslavvolkov** [comment]
Sorry guys, that is usually breaks on switching back and forth between different IDEs trying to align shared fixes.

Thanks for report, will publish in couple days

**Comment by vladyslavvolkov** [comment]
Upcoming fix in 2023.9.24
