### ISSUE TITLE
Warning messages not displayed properly with Hiberbee Theme

### ISSUE THREAD

**Issue by CCnevergiveup** [Hiberbee/code-highlight-themes#105]
**Describe the bug**
When using JetBrains IDEA 2023.2.1 on Windows 11 21H2, warning messages such as "Unsafe query: 'Delete' statement without 'where' clears all data in the table" are not displayed properly when using the Hiberbee Theme plugin version 2023.9.18.1533.

Specifically, the warning text overlaps with the IDE interface elements, making it difficult to read the message. This issue does not occur with the default IDEA themes.

**To Reproduce**
1.Install Hiberbee Theme plugin version 2023.9.18.1533 in IDEA 2023.2.1
2.Run an unsafe SQL delete query in the database tool window
3.Observe warning message display

**Screenshots**
![image](https://github.com/hiberbee/themes/assets/49151000/4faea04d-3a43-48ce-9f9c-11c4a2fed247)

**Desktop :**
 - OS: Windows
 - Version:  Windows 11 21H2,IDEA 2023.2.1,Hiberbee Theme  2023.9.18.1533

**Comment by vladyslavvolkov** [comment]
@CCnevergiveup thanks, not sure if I was able to reproduce that scenario correctly to fix up that thing, so please, let me know after updating to v2023.9.24. Thanks

**Comment by CCnevergiveup** [comment]
After updating to v2023.9.24, this issue has been successfully fixed. Thanks
