### ISSUE TITLE
IntelliJ (New UI) Buttons Run, Debug, ... are invisible

### ISSUE THREAD

**Issue by aronschmidt** [Hiberbee/code-highlight-themes#109]
**Describe the bug**
The buttons to run or debug an application in the top right corner of Intellij are not visible. I'm using the New UI.

**Expected behavior**
Buttons are visible

**Screenshots**
![grafik](https://github.com/hiberbee/themes/assets/47109469/37b90237-628c-4772-b625-f33c3314b75e)

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.6.1
 - IntelliJ IDEA 2023.2.4 (Ultimate Edition)
 - Version 2023.11.4.1839

**Comment by vladyslavvolkov** [comment]
@aronschmidt i've published update, and that bug should be fixed, so wanna close this issue. As I have no macOS env up and running, there is a small chance that bug still make sense, so feel free to reopen this one.

While on moderation, dist `jar` is available for manual update in latest release assets. 

Hope that will not be needed 🙏🏻
