### ISSUE TITLE
There is no way to choose the theme.

### ISSUE THREAD

**Issue by RuslanSafa** [Hiberbee/code-highlight-themes#12]
Тема установлена. Но ее нет не в цветовых схемах, не в выборе темы IDE. IDEA 2019.1

En: Installed this theme, but there is no options where I can choose theme. Neither in Appearance, neither in color scheme.

<img width="1266" alt="Снимок экрана 2019-11-13 в 15 57 09" src="https://user-images.githubusercontent.com/36810919/68765927-f82a3780-062e-11ea-8f8e-90e750e01dd1.png">
<img width="872" alt="Снимок экрана 2019-11-13 в 15 58 40" src="https://user-images.githubusercontent.com/36810919/68765929-f82a3780-062e-11ea-8657-a9951d44b480.png">
<img width="872" alt="Снимок экрана 2019-11-13 в 15 59 12" src="https://user-images.githubusercontent.com/36810919/68765930-f8c2ce00-062e-11ea-8a83-25e87b60207f.png">

**Comment by vladyslavvolkov** [comment]
Hi, Ruslan,

not sure is that still relevant?
Sorry, not very active since all major issues fixed, just losing those notifications in the feed

**Comment by RuslanSafa** [comment]
@vladyslavvolkov  Actually, the problem is not solved

**Comment by vladyslavvolkov** [comment]
Which versions of IDE & plugin do you use?

**Comment by RuslanSafa** [comment]
After upgrading to 1.7, it worked.
