### ISSUE TITLE
invalid color reference in .theme.json file

### ISSUE THREAD

**Issue by DevCharly** [Hiberbee/code-highlight-themes#13]
I'm using your .theme.json file in a Demo for a Swing look and feel
(https://github.com/JFormDesigner/FlatLaf) and found that there is
a invalid color reference in the json file.

~~~
"CheckBoxMenuItem.disabledBackground": "darkBackground",
~~~

`darkBackground` does not exist.

https://github.com/Hiberbee/code-highlight-themes/blob/master/src/main/resources/Hiberbee.theme.json#L67

**Comment by vladyslavvolkov** [comment]
@DevCharly thanks, sorry for late response,

that was kind a typo - fixed in last commit & renamed colors for better readability.

Let me know if any additional changes required

**Comment by DevCharly** [comment]
@vladyslavvolkov thanks for the fix

But the progress bar is now broken. It is all yellow because `ProgressBar.progressColor` and `ProgressBar.trackColor` use the same yellow color. You should use a gray color for `ProgressBar.trackColor`.

**Comment by vladyslavvolkov** [comment]
@DevCharly yep, missed that, thatnks. Fixed in 1.6.3

**Comment by DevCharly** [comment]
Thx
