### ISSUE TITLE
Default selection foreground/background too similar

### ISSUE THREAD

**Issue by smparekh** [Hiberbee/code-highlight-themes#14]
The default selection foreground/background properties make it hard to distinguish the selected region from the rest of the text:
<img width="1154" alt="Screen Shot 2020-01-06 at 3 27 19 PM" src="https://user-images.githubusercontent.com/2242057/71846734-44c34980-3099-11ea-9627-361047254ea5.png">
In the above example the region `factor` is highlighted in the word `refactoring`

I think the foreground/background color values should be updated to provide clear indication of the selected regions:
<img width="1154" alt="Screen Shot 2020-01-06 at 3 28 07 PM" src="https://user-images.githubusercontent.com/2242057/71846790-691f2600-3099-11ea-9f19-52e07dae6d32.png">

**Comment by vladyslavvolkov** [comment]
Hi @smparekh, agree with you

I've updated in 1.8.1 selection colors. The biggest challenge is to keep syntax hightlight and make it contrast at the same time. Will rethink on that soon.

Should be published in day or two. Let me know if could be any better

**Comment by smparekh** [comment]
Thanks Vlad, I will let you know if I can think of any way to make it better.
