### ISSUE TITLE
Theme stop working after last update

### ISSUE THREAD

**Issue by calebeaires** [Hiberbee/code-highlight-themes#17]
Webstorm 2020.1
MacOS

After update the theme stop working into Color Schema **Editor**, but works in interface

<img width="1181" alt="Screen Shot 2020-04-09 at 11 18 22" src="https://user-images.githubusercontent.com/794195/78905101-dbfebb00-7a53-11ea-8e94-598dc092a4b3.png">

**Comment by AgentOfTech** [comment]
It's also not working on the latest versions of IntelliJ and PhpStorm. Also, running the latest version of macOS.

**Comment by vladyslavvolkov** [comment]
Thanks guys, my bad, start splitting theme into light/dark colors and produce a typo. 

Plugin is on verification, should be available in day-two.

In case you wanna update just now, I've attached plugin JAR with latest release

https://github.com/Hiberbee/code-highlight-themes/releases/tag/1.9.3

**Comment by vladyslavvolkov** [comment]
@AgentOfTech @calebeaires did you have chance to update? Let me know if issue still relevant

**Comment by AgentOfTech** [comment]
Thanks for the update. Yes, it is now working. Just so everyone knows, it will appear as though it did not work after the IDE restarts. I went to Preferences > Appearance and Hiberbee Dark was selected. I switch it to Dracula, clicked Apply, and then switch it back to Hiberbee Dark, clicked Apply and then it started working great.
