### ISSUE TITLE
Selection isn't visible on editor's text

### ISSUE THREAD

**Issue by alexbeewise** [Hiberbee/code-highlight-themes#70]
When any part of code in PyCharm's editor is selected, the selection isn't visible because it is coloured black, while the background is dark grey.

**Expected behavior**
The contrast of the selection must be increased, by brightening the selection colour or changing it to a brighter one

**Screenshots**
![image](https://user-images.githubusercontent.com/99261199/165533762-dbdcfff6-c645-4069-98f0-02afa38b5cf9.png)

**Comment by vladyslavvolkov** [comment]
@alexbeewise thanks, fix will be available in new release in a couple of days

**Comment by errandir** [comment]
@VladyslavVolkov Are there any updates? Selections are still hardly distinguishable (in a code and in dialog window fields especially).

**Comment by vladyslavvolkov** [comment]
Will be live in next few days

**Comment by vladyslavvolkov** [comment]
Should be released in 2023.1.9 tag, use https://plugins.jetbrains.com/files/12118/274784/jetbrains-ide-theme-2023.1.9.1211.zip until moderation completes
