### ISSUE TITLE
Inactive tabs are no longer colored

### ISSUE THREAD

**Issue by nicoell** [Hiberbee/code-highlight-themes#72]
With the recent theme update, inactive tabs are no longer receiving file colors .

**To Reproduce**
Steps to reproduce the behavior (in Rider 2022.1):
1. Go to Settings > Appearance & Behaviour > File Colors
2. Setup file colors for a scope.
3. Enable "Use in editor tabs"
4. See that inactive tabs do not receive file color.

**Expected behavior**
Inactive tabs should receive file colors. It is the case in all preset themes from Jetbrains.

**Screenshots**
Screenshot using Hiberbee Dark:
![image](https://user-images.githubusercontent.com/4254495/171797221-1f4074c2-358c-4be6-957f-50de6099a860.png)
Screenshot using Visual Studio Dark:
![image](https://user-images.githubusercontent.com/4254495/171797278-e6b0a1aa-0c1b-43f8-8b35-fa6b37b5eec3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Rider 2022.1

**Additional context**
I think it might be related to recent change and this setting:
[      "inactiveColoredFileBackground": "editorPaneBg",](https://github.com/hiberbee/jetbrains-ide-theme/blob/8e91144006b84236b138d9a325f57f80012db7e2/src/main/resources/HiberbeeDark.theme.json#L166)

**Comment by vladyslavvolkov** [comment]
@nicoell thanks, should be fixed in upcoming 2022.11.27.0537
