### ISSUE TITLE
Grey maven parent poms

### ISSUE THREAD

**Issue by mhibberd-dirtt** [Hiberbee/code-highlight-themes#74]
I believe this theme suffers from the same issue documented below in the material theme.
https://github.com/ChrisRM/material-theme-jetbrains/issues/1491

Projects with parent pom.xml files show the entire contents of the parent pom.xml as grey text. And the section in child pom.xml files that describes the parent are also grey.

I believe the fix is to add 'parent_scheme="Default"' to line 1 in \src\main\resources\colors\Dark.xml to become:
<scheme name="Hiberbee Dark" version="142" parent_scheme="Default">

Couldn't seem to get the gradle build working for this repo. So I dug through the plugins and manually changed the file in the .jar and it seems to work fine for me now. Would be great if you could apply the fix into the repo and get a new version out.

**Comment by vladyslavvolkov** [comment]
@mhibberd-dirtt thanks, should be fixed in upcoming 2022.11.27.0537
