### ISSUE TITLE
New Android Studio Logcat theme overwritten 

### ISSUE THREAD

**Issue by tyczj** [Hiberbee/code-highlight-themes#80]
**Describe the bug**
The new logcat in android studio version Dolphin has a new logcat view and the theme changes the colors of the log level messages so its harder to identify.

**To Reproduce**
1. Download Android Studio Dolphin
2. View LogCat and compare with default theme

**Expected behavior**
Support the updated look of the logcat ie. color error/warning messages in red/yellow etc. as well as the log level letter

**Screenshots**

Screenshot with Hiberbee on
![image](https://user-images.githubusercontent.com/1816052/190681046-965db73c-ef67-4c96-a3c8-f0771d78048b.png)

Screenshot with default theme
![image](https://developer.android.com/static/studio/images/releases/logcat-logs.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by vladyslavvolkov** [comment]
@tyczj i've made some changes in latest build, which should be available in day or two.
Please, let me know if that works (i am not using Android Studio on daily basis)

**Comment by tyczj** [comment]
Log message colors are still off they are still all grey vs warnings being yellow and errors being red

Default
![image](https://user-images.githubusercontent.com/1816052/205983736-023d5e6b-e7a3-4bc3-b430-8597617c43ea.png)

Hiberbee
![image](https://user-images.githubusercontent.com/1816052/205983976-2338ee3d-5a32-4b4d-bc36-6d7945c41b2a.png)

Makes it a bit harder to find error messages in the logs

**Comment by vladyslavvolkov** [comment]
Seems like after merging colors from Android Studio in IntelliJ they are overwritten as unsupported.

Have to dive deeper into that, will try to back soon with sort of solution

**Comment by vladyslavvolkov** [comment]
@tyczj actually I have colors applied, with latest available update in marketplace.
![Screenshot 2022-12-07 071355](https://user-images.githubusercontent.com/1200484/206094423-ee83ff49-f90e-4052-9db5-31a7220bc14f.png)

Could you check if your theme settings changed? Would appreciate if you share similar screenshot.

Thanks in advance
