### ISSUE TITLE
Broken on WebStorm

### ISSUE THREAD

**Issue by gardamork** [Hiberbee/code-highlight-themes#84]
**Describe the bug**
The latest version breaks installing on WebStorm versions pre-2022.3 with error:

> Plugin "Hiberbee Theme" was not installed: Downloaded version is incompatible with the current IDE: Plugin 'Hiberbee Theme' (version '2022.11.19.0023') is not compatible with the current version of the IDE, because it requires build 223 or newer but the current build is WS-222.4345.14

**To Reproduce**
1. Install Hiberbee Theme on WebStorm pre-2022.3

**Expected behavior**
The theme to install on compatible versions 191+

**Screenshots**
![image](https://user-images.githubusercontent.com/52025349/203275815-4c1c27c5-c780-4df4-96cb-cc50ab9795ee.png)

**Desktop (please complete the following information):**
 - OS: macOS 13.0.1 on M1 Pro
 - Version: 2022.11.19.0023
 - IDE: WebStorm 2022.2.3 (WS-222.4345.14)

**Comment by cleanbit** [comment]
Same thing with PyCharm 2022.2.4

`Plugin "Hiberbee Theme" was not installed: Downloaded version is incompatible with the current IDE: Plugin 'Hiberbee Theme' (version '2022.11.19.0023') is not compatible with the current version of the IDE, because it requires build 223 or newer but the current build is PY-222.4459.20`

**Comment by hutstep** [comment]
Same with Rider 2022.2.4

![image](https://user-images.githubusercontent.com/18348355/203328590-72b412b8-8e0f-4f3a-b952-9ccc088e012e.png)

**Comment by worldunseen** [comment]
Looks like a recent commit may have broken the update; I see some properties that check for build number have been removed: https://github.com/hiberbee/jetbrains-ide-theme/commit/ce2b385bb918ec2f9203c987b79baa53d8465f1a#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19

**Comment by vladyslavvolkov** [comment]
Guys, should be fixed now. Let me know if that issue stil valid. Appreciate
