### ISSUE TITLE
Oh, no!!!! Tabs are bright grey!

### ISSUE THREAD

**Issue by alexbeewise** [Hiberbee/code-highlight-themes#85]
Hello, @VladyslavVolkov 

In the last update, the colors of inactive opened file tabs were changed to bright grey. The color comes with a contrast to the rest of the dark theme and is highly disharmonic.
Please revert this change or significantly darken the color.

Also, the checkboxes in different menus are completely unreadable: the check mark is almost invisible. Screenshot attached.

![image](https://user-images.githubusercontent.com/99261199/204466793-fb4117fc-b909-4a17-84a5-2c4547c678a6.png)

Thanks!

**Comment by alexbeewise** [comment]
The following solution seems very nice to me:

![image](https://user-images.githubusercontent.com/99261199/204490805-765f333d-7b6c-4645-9f12-a3e64fab90a7.png)

(c) taken from Visual Studio Code Dark Plus theme

**Comment by LukeyR** [comment]
Also an issue for me. Cant find where i can manually override this colour value in settings, if anyone knows where this is?

**Comment by vladyslavvolkov** [comment]
Guys, fix on JB review now for couple days, but you can install manually via [link](https://plugins.jetbrains.com/plugin/download?rel=true&updateId=259098)

Let me know if that looks good or need extra effort

**Comment by alexbeewise** [comment]
@VladyslavVolkov 
much better :) Thanks for the prompt fix! I can return to my favourite theme now 👍🏻
