### ISSUE TITLE
Make Project Tree more compact

### ISSUE THREAD

**Issue by michael-farwell** [Hiberbee/code-highlight-themes#88]
Is there a way to make the project tree a bit more compact or have an option to do so? Similar to the screenshot below would be great. 
![Screenshot 2022-12-27 at 7 06 07 AM](https://user-images.githubusercontent.com/21293442/209664442-054f6cea-9898-44cc-869f-ec2479bc1c9b.png)

**Comment by vladyslavvolkov** [comment]
@michael-farwell if I got your idea, you can decrease indents in Settings - `File | Settings | Appearance & Behavior | Appearance > UI Options > Use smaller indents in trees`. This parameters is not managed by theme

**Comment by michael-farwell** [comment]
@VladyslavVolkov I was meaning the vertical space between the folders.
However, I did just update to 2022.12.27.1554 which appears to have fixed that. Thank you!
