### ISSUE TITLE
checkboxes colors are unsuitable

### ISSUE THREAD

**Issue by alexbeewise** [Hiberbee/code-highlight-themes#89]
Hello,

after the latest update, the colors of checkboxes don't let distinguish between checked and un-checked boxes. The mark is white on a yellow checkbox.
See the attached screenshot.
![image](https://user-images.githubusercontent.com/99261199/209676275-9c6e2aeb-ac33-4135-9ff7-4d0d3a7d5171.png)

**Comment by vladyslavvolkov** [comment]
Hi @alexbeewise 

today released patch, seems like issue is gone 
![image](https://user-images.githubusercontent.com/1200484/209700200-1079afa4-af68-45bd-aade-28793849acd3.png)

Please, confirm if that is correct

**Comment by alexbeewise** [comment]
Hi,
I've updated the plugin, but on my side nothing has changed.

![image](https://user-images.githubusercontent.com/99261199/209807850-aadcbe69-3e80-4013-bd3e-20a835b2be30.png)

This is my version of PyCharm:
PyCharm 2022.2.4 (Professional Edition)
Build #PY-222.4459.20, built on November 17, 2022
Runtime version: 17.0.5+7-b469.71 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins:
    monokai-pro (1.10)
    com.samdark.intellij-visual-studio-code-dark-plus (2.6)
    com.obroom.plugin.smartsearch (2022.6.1)
    com.hiberbee.intellij.hiberbee-theme (2022.12.27.1544)
    izhangzhihao.rainbow.brackets (2022.3.5-ij)

**Comment by vladyslavvolkov** [comment]
Okay, i see, that is new Ui feature enabled in my case. Let me figure out with fallback solution

**Comment by vladyslavvolkov** [comment]
Yep, discovered that in new UI checkboxes are actually link ancestors. Bad news that I was not able to match all properties for both old and new UI components. Good news that I fixed checkbox ugly view you experiencing. On screenshot left side is new experimental UI 2022.3, right side - 2022.2 old one. 
![image](https://user-images.githubusercontent.com/1200484/209815799-152f953c-fa05-4161-943f-d5a5e9ba2213.png)

**Comment by vladyslavvolkov** [comment]
Build is upcoming, you can use [direct link](https://plugins.jetbrains.com/files/12118/271010/Hiberbee_theme-2022.12.28.1500.zip) for manual install either

Thanks for feedback

**Comment by alexbeewise** [comment]
Yep, your last update has fixed the issue.
Thank you for the prompt handling.
