### ISSUE TITLE
Text marking not visible in Evaluate Expression window (single-line)

### ISSUE THREAD

**Issue by P1zz4br0etch3n** [Hiberbee/code-highlight-themes#9]
First of all thank you very much for this beautiful theme! I like it a lot more than the shipped Darcula theme.

There's only one thing that really annoys me. Whenever I'm in debugging mode and want to evaluate an expression I click on the expression in my code and then open the "Evaluate Expression" window. The clicked expression will be filled into the Expression input and marked completely. But since I don't see that it's marked I just start typing like if my cursor was at the end of the expression and therefore it disappears and only what I typed in will remain. This is only the case in single-line mode. If I change the input to multi-line, the marking of text is visible. 

I hope you can confirm this issue. Looking forward to see this fixed in a future version.

**Comment by vladyslavvolkov** [comment]
Thanks for reporting, yep, debugging is not really aligned with theme.

I've sent update, 1.3.4, should be availble in next couple of days.

Should also fix #8, if still makes sence (I've not reproduce on 2019.2.1)

**Comment by P1zz4br0etch3n** [comment]
Thanks for your quick answer. I just updated to 1.3.4 but the issue is still there for me.

In the screenshot the expression 'consumer' is marked but it looks like this:
![Bildschirmfoto vom 2019-08-20 10-58-56](https://user-images.githubusercontent.com/9010623/63333338-944ae800-c339-11e9-885b-6d597a6d484b.png)

Tested with Intellij 2019.1 and 2019.2. I still use 2019.1 because the python plugin is broken in 2019.2. So obviously this happens to me in debugging python code, if that makes any difference. Do you need more information?

**Comment by vladyslavvolkov** [comment]
No, that's it, will test on Python today. So, just curious, it should be highlighted with one of bright colors? Cause never used in such context

**Comment by P1zz4br0etch3n** [comment]
Yes. If i switch back to Darcular theme it looks like this:
![Bildschirmfoto vom 2019-08-20 12-30-43](https://user-images.githubusercontent.com/9010623/63340075-83ed3a00-c346-11e9-8aad-85b646faa01d.png)

**Comment by vladyslavvolkov** [comment]
Yeah, got it. Issue was not only in debug selection, but in other textfields / textareas.

While 1.3.6 approving on JB, you can install from disk

[hiberbee-1.3.6.zip](https://github.com/Hiberbee/intellij-theme/files/3520224/hiberbee-1.3.6.zip)

**Comment by P1zz4br0etch3n** [comment]
Thanks a lot! I can confirm that the issue is gone in 2019.2. But in 2019.1.4, which I use, it's still there for some reason. Hope they fix the python plugin soon.

**Comment by P1zz4br0etch3n** [comment]
I now updated to 2019.2.1 and it stopped working. Also on 2019.2 it doesn't work any more. Just to be sure, when I faced the working state the highlight colour was darker than the input background. That is that intended, right?

Off topic: Turns out there is no python plugin issue but a docker plugin issue. After disabling that, python works just fine in 2019.2(.1)

**Comment by P1zz4br0etch3n** [comment]
I'm sorry but this is not closed to me. I still face the issue in 2019.2.3. Is there nobody using the evaluate expression function?

**Comment by P1zz4br0etch3n** [comment]
Thanks for the update! Now I see a very slightly difference between marked text background (#404040) and textbox background (#3C3C3C). If you increase the contrast this can be closed.

![Bildschirmfoto vom 2019-11-06 16-36-06](https://user-images.githubusercontent.com/9010623/68313280-97da4980-00b4-11ea-88dc-44a1259e6ece.png)

**Comment by vladyslavvolkov** [comment]
Hola, seems to find the required combobox finally. It's a big confusion between theme versus code style colors, as well as form elements. 

Pushed 1.5.1 update, and updated repository. If you see extra colors need refreshment, let me know.

**Comment by P1zz4br0etch3n** [comment]
Gosh, now I know what the problem is! The color we are looking for is the SELECTION_BACKGROUND in the editor color scheme general. But because for me it is too close to the editors TEXT BACKGROUND I changed it on my machine to a lighter color which is very close to the background color of the Textbox in the Evaluate Expression window. I didn't mind that it's the same color used in both places. I'm sorry! Thank you anyway for your effort!
