### ISSUE TITLE
yellow background in code completion makes it unreadable

### ISSUE THREAD

**Issue by hutstep** [Hiberbee/code-highlight-themes#92]
I'm using Rider 2022.3.1 and Hiberbee 2023.01.12.0712.
When using code completion, background is yellow and font is light grey, which makes it unreadable.
I also tried New UI, but same issue.

![image](https://user-images.githubusercontent.com/18348355/214239076-c00252a2-49fc-4e84-873d-6ec765ecab7f.png)

**Comment by vladyslavvolkov** [comment]
@hutstep check please, should be fixed as of 2023.1.30 release
